<?php

return [
    'VEGUNIT' => [
        'REMOVCAT',
        'UNIT',
        'DESIGNATION',
        'EDITDATE',
        'STUMPHERB',
        'SPECIES',
        'FORESTER',
        'PERMSTAT',
        'DATEPOP',
        'ASSDDATE',
        'ASSNOTE',
        'PARCELCOMMENTS',
        'FIRSTNAME',
        'LASTNAME',
        'TFIRSTNAME',
        'TLASTNAME',
        'CPHONE',
        'CFIRSTNAME',
        'CLASTNAME',
        'PADDRESS',
        'CADDRESS',
        'CCITY',
        'CSTATE',
        'CZIP',
        'TADDRESS',
        'TCITY',
        'TSTATE',
        'TZIP',
        'ADDRESS',
        'CITY',
        'STATE',
        'ZIPCODE',
        'TOWN',
        'NOTIFTYPE',
        'NOT2FY',
        'NOTIFDATE',
        'AUDITOR',
        'AUDIT_FAIL',
        'AUDIT_USER',
        'AUDITDATE',
        'AUDITNOTE',
        'AUDITCOMMENTS',
        'TPHONE',
        'FROMSTR',
        'TOSTR',
        'POLE_A',
        'POLE_B',
    ],

    'Stations' => [
        'STATNAME',
        'SPANLGTH',
    ],
];
